#!/bin/sh
#
# depend2mk: Convert gcc "-MD" or CPP auto-generate dependencies
#            into something a little more sane.
#
# Copyright Alan T. DeKok
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# depend2mk
#	${BUILD_DIR}
#	$(dir $${MAKE_DIR}/src/$(basename ${1}).mk)
#	$${BUILD_DIR}/objs/$(basename ${1}).d
#	$${MAKE_DIR}/src/$(basename ${1}).mk
#
mkdir -p $2 || exit 1
sed  -e 's/#.*//' -e 's, /[^: ]*,,g' -e 's,^ *[^:]* *: *$,,' -e '/: </ d' -e 's/\.o: /.${OBJ_EXT}: /' -e '/^ *\\$/ d' -e "s,^$1,\${BUILD_DIR}," -e '/^$/ d' < $3 | sed -e '$!N; /^\(.*\)\n\1$/!P; D' > $4 || exit 2
sed -e 's/#.*//' -e 's, /[^: ]*,,g' -e 's,^ *[^:]* *: *$,,' -e '/: </ d' -e 's/^[^:]*: *//' -e 's/ *\\$//' -e '/^$/ d' -e 's/$/ :/' < $3 | sed -e '$!N; /^\(.*\)\n\1$/!P; D' >> $4 || exit 3
rm -f $3 || exit 4
