# Boilermake includes a number of files.  One method of using them is to
# copy all of the files to the top directory of your project.  However,
# this can "pollute" your application with a lot of files.
#
# A simpler way is to put all of the Boilermake files into another directory.
# The top "Makefile" of your application can just include the main
# Boilermake file, and Boilermake will figure everything out from there.
#
# For this example test-app, we use the files in the directory above.
# But we could have just put the files into a "boilermake" sub-directory,
# and done "include ./boilermake/Makefile"
#
include ../../Makefile
