.TH talk 1 "1 April 2000" "" "talk program"
.SH NAME
talk - sample program
.SH SYNOPSIS
.B talk
.SH DESCRIPTION
\fBtalk\fP is an example program build by the boilermake system.  It is
intended to demonstrate how to use boilermake.  It is not intended to
do anything useful.

It should not be installed.

.SH AUTHORS
Alan DeKok <aland@freeradius.org>

